// <auto-generated />
using System;
using FitnessApp.Modules.Users.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessApp.Modules.Users.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20250820000000_AddRoleAndSubscription")]
    partial class AddRoleAndSubscription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Cette méthode est générée automatiquement par EF Core, 
            // mais elle n'est pas essentielle pour la migration
        }
    }
}
