using System.ComponentModel;

namespace FitnessApp.SharedKernel.Enums;

/// <summary>
/// Defines the type of workout based on how it was created
/// </summary>
public enum WorkoutType
{
    [Description("Pre-built workout available to all users")]
    Template = 0,

    [Description("Custom workout created by the user")]
    UserCreated = 1,

    [Description("Workout generated by AI based on program objectives")]
    AIGenerated = 2
}

/// <summary>
/// Defines the category/style of workout
/// </summary>
public enum WorkoutCategory
{
    [Description("Cardiovascular endurance training")]
    Cardio = 0,

    [Description("Strength and muscle building")]
    Strength = 1,

    [Description("Flexibility and mobility")]
    Flexibility = 2,

    [Description("High-intensity interval training")]
    HIIT = 3,

    [Description("Functional movement patterns")]
    Functional = 4,

    [Description("Balance and stability")]
    Balance = 5,

    [Description("Mixed workout combining multiple elements")]
    Mixed = 6
}

/// <summary>
/// Defines the different phases of a workout
/// </summary>
public enum WorkoutPhaseType
{
    [Description("Warm-up phase to prepare the body")]
    WarmUp = 0,

    [Description("Main effort phase containing the core exercises")]
    MainEffort = 1,

    [Description("Recovery phase")]
    Recovery = 2,

    [Description("Cool-down phase after main effort")]
    CoolDown = 3,

    [Description("Stretching phase")]
    Stretching = 4
}

/// <summary>
/// Defines different types of exercise metrics
/// </summary>
public enum ExerciseMetricType
{
    [Description("Time-based exercise (e.g., plank)")]
    Time = 0,

    [Description("Repetition-based exercise")]
    Repetitions = 1,

    [Description("Distance-based exercise")]
    Distance = 2,

    [Description("Weight-based exercise")]
    Weight = 3
}
