// <auto-generated />
using System;
using FitnessApp.Modules.Workouts.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitnessApp.Modules.Workouts.Infrastructure.Migrations
{
    [DbContext(typeof(WorkoutsDbContext))]
    partial class WorkoutsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("workouts")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitnessApp.Modules.Workouts.Domain.Entities.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedByCoachId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<double>("EstimatedDuration")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("ImageContentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RequiredEquipment")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedByCoachId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Difficulty");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.HasIndex("RequiredEquipment");

                    b.HasIndex("Type");

                    b.HasIndex("IsActive", "CreatedAt");

                    b.HasIndex("Type", "Difficulty");

                    b.ToTable("workouts", "workouts");
                });

            modelBuilder.Entity("FitnessApp.Modules.Workouts.Domain.Entities.WorkoutExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkoutPhaseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("Order");

                    b.HasIndex("WorkoutPhaseId");

                    b.HasIndex("WorkoutPhaseId", "Order")
                        .IsUnique();

                    b.ToTable("workout_exercises", "workouts");
                });

            modelBuilder.Entity("FitnessApp.Modules.Workouts.Domain.Entities.WorkoutPhase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("EstimatedDuration")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Order");

                    b.HasIndex("Type");

                    b.HasIndex("WorkoutId");

                    b.HasIndex("WorkoutId", "Order")
                        .IsUnique();

                    b.ToTable("workout_phases", "workouts");
                });

            modelBuilder.Entity("FitnessApp.Modules.Workouts.Domain.Entities.WorkoutExercise", b =>
                {
                    b.HasOne("FitnessApp.Modules.Workouts.Domain.Entities.WorkoutPhase", "WorkoutPhase")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutPhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FitnessApp.Modules.Workouts.Domain.ValueObjects.ExerciseParameters", "Parameters", b1 =>
                        {
                            b1.Property<Guid>("WorkoutExerciseId")
                                .HasColumnType("uuid");

                            b1.Property<long?>("Duration")
                                .HasColumnType("bigint")
                                .HasColumnName("duration_seconds");

                            b1.Property<string>("Notes")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("notes");

                            b1.Property<int?>("Reps")
                                .HasColumnType("integer")
                                .HasColumnName("reps");

                            b1.Property<long?>("RestTime")
                                .HasColumnType("bigint")
                                .HasColumnName("rest_time_seconds");

                            b1.Property<int?>("Sets")
                                .HasColumnType("integer")
                                .HasColumnName("sets");

                            b1.Property<double?>("Weight")
                                .HasPrecision(5, 2)
                                .HasColumnType("double precision")
                                .HasColumnName("weight");

                            b1.HasKey("WorkoutExerciseId");

                            b1.ToTable("workout_exercises", "workouts");

                            b1.WithOwner()
                                .HasForeignKey("WorkoutExerciseId");
                        });

                    b.Navigation("Parameters")
                        .IsRequired();

                    b.Navigation("WorkoutPhase");
                });

            modelBuilder.Entity("FitnessApp.Modules.Workouts.Domain.Entities.WorkoutPhase", b =>
                {
                    b.HasOne("FitnessApp.Modules.Workouts.Domain.Entities.Workout", "Workout")
                        .WithMany("Phases")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("FitnessApp.Modules.Workouts.Domain.Entities.Workout", b =>
                {
                    b.Navigation("Phases");
                });

            modelBuilder.Entity("FitnessApp.Modules.Workouts.Domain.Entities.WorkoutPhase", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
