// <auto-generated />
using System;
using FitnessApp.Modules.Tracking.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitnessApp.Modules.Tracking.Infrastructure.Migrations
{
    [DbContext(typeof(TrackingDbContext))]
    [Migration("20250926071336_TrackingModule_Initial")]
    partial class TrackingModule_Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tracking")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitnessApp.Modules.Tracking.Domain.Entities.PlannedWorkout", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsFromProgram")
                        .HasColumnType("boolean")
                        .HasColumnName("is_from_program");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_id");

                    b.Property<Guid?>("WorkoutSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_session_id");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.HasIndex("ScheduledDate");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutId");

                    b.HasIndex("WorkoutSessionId");

                    b.HasIndex("UserId", "ScheduledDate");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("planned_workouts", "tracking");
                });

            modelBuilder.Entity("FitnessApp.Modules.Tracking.Domain.Entities.UserMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MetricType")
                        .HasColumnType("integer")
                        .HasColumnName("metric_type");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<double>("Value")
                        .HasPrecision(10, 4)
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("MetricType");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "MetricType");

                    b.HasIndex("UserId", "MetricType", "RecordedAt");

                    b.ToTable("user_metrics", "tracking");
                });

            modelBuilder.Entity("FitnessApp.Modules.Tracking.Domain.Entities.WorkoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("CaloriesEstimated")
                        .HasColumnType("integer")
                        .HasColumnName("calories_estimated");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsFromProgram")
                        .HasColumnType("boolean")
                        .HasColumnName("is_from_program");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("PerceivedDifficulty")
                        .HasColumnType("integer")
                        .HasColumnName("perceived_difficulty");

                    b.Property<DateTime?>("PlannedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_date");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("total_duration_seconds");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlannedDate");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutId");

                    b.HasIndex("UserId", "StartTime");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("workout_sessions", "tracking");
                });

            modelBuilder.Entity("FitnessApp.Modules.Tracking.Domain.Entities.WorkoutSessionExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("exercise_name");

                    b.Property<int>("MetricType")
                        .HasColumnType("integer")
                        .HasColumnName("metric_type");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<double?>("PerformanceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision")
                        .HasColumnName("performance_score");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkoutSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_session_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("PerformedAt");

                    b.HasIndex("WorkoutSessionId");

                    b.HasIndex("WorkoutSessionId", "Order");

                    b.ToTable("workout_session_exercises", "tracking");
                });

            modelBuilder.Entity("FitnessApp.Modules.Tracking.Domain.Entities.WorkoutSessionSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Distance")
                        .HasColumnType("double precision");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("Repetitions")
                        .HasColumnType("integer");

                    b.Property<int?>("RestTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision");

                    b.Property<Guid>("WorkoutSessionExerciseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutSessionExerciseId");

                    b.ToTable("WorkoutSessionSet", "tracking");
                });

            modelBuilder.Entity("FitnessApp.Modules.Tracking.Domain.Entities.WorkoutSessionExercise", b =>
                {
                    b.HasOne("FitnessApp.Modules.Tracking.Domain.Entities.WorkoutSession", "WorkoutSession")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("FitnessApp.Modules.Tracking.Domain.Entities.WorkoutSessionSet", b =>
                {
                    b.HasOne("FitnessApp.Modules.Tracking.Domain.Entities.WorkoutSessionExercise", "WorkoutSessionExercise")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutSessionExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutSessionExercise");
                });

            modelBuilder.Entity("FitnessApp.Modules.Tracking.Domain.Entities.WorkoutSession", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("FitnessApp.Modules.Tracking.Domain.Entities.WorkoutSessionExercise", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
